[package]
name = "mesos"
version = "0.1.0"
authors = ["storyfeet <thebeaky@psmail.net>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
default-target="mesos.json"

[dependencies]
bootloader_precompiled = "0.2.0"
volatile = "0.2.3"

